### ISSUE TITLE
Bug calculating WER with special characters

### ISSUE THREAD

**Issue by carmocca** [Transkribus/TranskribusErrorRate#4]
Hello,

Given the following lines:
ref: `1 s 2`
hyp: `1 s 3`

and calling: `java -cp TranskribusErrorRate-2.2.7 eu.transkribus.errorrate.HtrErrorTxt ref hyp --wer`
does give the correct result: `ERR=0.3333333333333333`

However, this does not:
ref: `1 <s 2`
hyp: `1 <s 3`
result: `ERR=0.25`

Conversely, it does work correctly if a single character is used:
ref: `1 < 2`
hyp: `1 < 3`
result: `ERR=0.3333333333333333`
or if no special characters are used:
ref: `1 ss 2`
hyp: `1 ss 3`
result: `ERR=0.3333333333333333`

The same behaviour can be reproduced with other characters such as "@" or "_".

Any idea on what's the problem?
Thank you.

**Comment by gundramleifert** [comment]
Dear @carmocca,

The problem is the tokenizer. The String `"1 s 2"` is tokenized (as you expect) in `["1", "s", "2"]`, whereas for `"1 <s 2"` you get `["1", "<" "s", "2"]`. If you calculate the ERR with this tokenization, `ERR=0.25` is correct.

now, the question is: **Why?**
If you ask people how many "words" have "`it's"` you will probably get the answers "1", "2" and "3". And we had long (!!) discussions about "What is a word?".

We follow the idea to split the string according their Unicode general category
https://github.com/Transkribus/TranskribusLanguageResources/blob/c914af481bff8a5c337dda9783746f35e96fbae9/TranskribusTokenizer/src/main/java/eu/transkribus/tokenizer/categorizer/CategorizerWordDft.java
https://en.wikipedia.org/wiki/Template:General_Category_(Unicode)

The rule (with an exception for `\n'):

- separate characters from different categories into different tokens

- delete all tokens from category `Separator (Z)`

**Configuration:**
have a look at the help of HtrErrorTxt. If you add the options `-c mycategory.txt` which points to a text-file with a character-category-map

```
<=L
```
your character `<` is pointed to the Letter-category (where `s` is part from). Then your above example should be changed from `ERR=0.25` to `ERR=0.33`. 

The last option is to create your own tokenizer and use it. If this is still an option, please tell me.

**Comment by rogerlabahn** [comment]
Moin & super ... genau so soll's sein!

Dank & Gruß noch von unterwegs
   Roger

Am 20. Juli 2020 08:50:32 MESZ schrieb Gundram Leifert <notifications@github.com>:
>Dear @carmocca,
>
>The problem is the tokenizer. The String `"1 s 2"` is tokenized (as you
>expect) in `["1", "s", "2"]`, whereas for `"1 <s 2"` you get `["1", "<"
>"s", "2"]`. If you calculate the ERR with this tokenization, `ERR=0.25`
>is correct.
>
>now, the question is: **Why?**
>If you ask people how many "words" have "`it's"` you will probably get
>the answers "1", "2" and "3". And we had long (!!) discussions about
>"What is a word"?
>
>We follow the idea to split the string according their Unicode general
>category
>https://github.com/Transkribus/TranskribusLanguageResources/blob/c914af481bff8a5c337dda9783746f35e96fbae9/TranskribusTokenizer/src/main/java/eu/transkribus/tokenizer/categorizer/CategorizerWordDft.java
>https://en.wikipedia.org/wiki/Template:General_Category_(Unicode)
>
>The rule (with an exception for `\n'):
>
>- separate characters from different categories into different tokens
>
>- delete all tokens from category `Separator (Z)`
>
>**Configuration:**
>have a look at the help of HtrErrorTxt. If you add the options `-c
>mycategory.txt` which points to a text-file with a
>character-category-map
>
>```
><=L
>```
>your character `<` is pointed to the Letter-category (where `s` is part
>from). Then your above example should be changed from `ERR=0.25` to
>`ERR=0.33`. 
>
>The last option is to create your own tokenizer and use it. If this is
>still an option, please tell me.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Transkribus/TranskribusErrorRate/issues/4#issuecomment-660838978

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by carmocca** [comment]
Thanks for the response!
